### ISSUE TITLE
로깅 AOP 구현

### ISSUE THREAD

**Issue by Dh3356** [mju-likelion/mju-festival-backend#108]
## Description
로깅 AOP 구현
### 로깅을 위한 toString 오버라이딩
- [x] SimpleAnnouncement
- [x] CreateAnnouncementRequest
- [x] UpdateAnnouncementRequest
- [x] AnnouncementDetailResponse
- [x] SimpleAnnouncementsResponse
- [x] AdminLoginRequest
- [x] UserLoginRequest
- [x] KeyResponse
- [x] LoginResponse
- [x] BoothDetail
- [x] SimpleBooth
- [x] UpdateBoothRequest
- [x] BoothDetailResponse
- [x] BoothQrResponse
- [x] SimpleBoothsResponse
- [x] ImageResponse
- [x] SimpleLostItem
- [x] CreateLostItemRequest
- [x] LostItemFoundRequest
- [x] UpdateLostItemRequest
- [x] SimpleLostItemsResponse
- [x] SimpleTerm
- [x] TermResponse
### 로깅 설정 파일 작성
- [x] logback-spring
### RequestIdInterceptor 작성 - 각 Request 에 ID 를 부여해 식별하기 위함
- [x] RequestIdInterceptor
- [x] WebConfig
### 로깅 AOP 
- [x] LoggingAspect
### ExceptionController 에서 로깅하지 않도록
- [x] ExceptionController
### ci-cd 스크립트 변경
- [x] ci-cd-develop
## Additional context

**Comment by Dh3356** [comment]
## 08/15 01:55 이슈 발생
현재: Aspect 를 사용해 로깅 중

문제: Interceptor의 preHandle 에서 문제 발생 시, Request 에 대한 로깅이 되지 않음

문제인 이유:
1. Aspect 는 Interceptor 후에 동작하므로
2. 악의적으로 권한 밖의 요청을 지속적으로 하는 유저에 대한 정보를 알 수 없음

**Comment by cookie-meringue** [comment]
## 08/16 01:30 해결책 제시
문제였던 이유: Aspect 가 Interceptor 이후에 동작하므로, Interceptor 의 preHandle 에서 생긴 문제(권한 문제)가 발생한 Request를 로깅할 수 없음 -> 악의적으로 권한 밖의 요청을 지속적으로 하는 유저에 대한 정보를 알 수 없음

---
### 해결책 1: 로깅을 Aspect 가 아닌 Interceptor 를 사용해 수행
- 해결책 1의 장점 1: 현재와 마찬가지로 "로깅" 이라는 것의 관심사를 하나의 인터셉터가 다룰 수 있음.

- 해결책 1의 단점 1: HttpServletRequest 의 Request Body는 한 번 읽으면 다시 읽을 수 없으므로 문제가 생기기 때문에, RequestWrapper를 사용하여 Request Body 캐싱해야 함. -> 복잡함.
- 해결책 1의 단점 2: Interceptor의 preHandle은 컨트롤러 메서드가 호출되기 전에 실행되기 때문에 Controller에 들어가는 직접적인 매개변수에 접근해 로깅할 수 없음.

---
### 해결책 2: AbstractAuthenticationInterceptor 는 인증/인가에 관한 Interceptor 임. 그러므로, 해당 Interceptor 의 preHandle 에서 HttpServletRequest 에 userId 를 set 하고, LoggingAspect 에서 해당 userId를 가져다 쓰면 악의적으로 권한 밖의 요청을 한 유저를 식별할 수 있음.

- 해결책 2의 장점 1: Controller 에 들어가는 직접적인 매개변수에 접근해 로깅하기 편리함
- 해결책 2의 장점 2: 추후 로깅 로직 변경 시, HTTP 메서드 단위로 변경 가능하기 때문에 변경이 용이함

- 해결책 2의 단점 1: "로깅"의 관심사에 대한 책임을 Aspect, 인증/인가 Interceptor 들이 지게 됨.

--- 
### 결론: 해결책 2 사용

- 근거 1: 인증/인가 Interceptor 들은 인증/인가 에 대한 책임을 지게 되어 있으니 인증/인가 에서 문제 발생 시 로깅할 수 있도록 userId 를 제공하는 것도 인증/인가의 책임 중 하나라고 판단함.
- 근거 2: Aspect는 Interceptor 에 비해 Controller 메서드에 전달되는 변수, 파라미터, 쿼리 스트링 등의 세부 정보를 편리하게 로깅 가능.
- 근거 3: 추후 로깅 로직이 변경될 시, Aspect가 Interceptor 보다 유연하게 변경이 가능함.

---
## 결론 - 인증/인가 인터셉터에서 예외가 발생하지 않았을 시 흐름
![image](https://github.com/user-attachments/assets/6faa2bf4-051e-4ba7-9968-50f84bbea46e)

---
## 결론 - 인증/인가 인터셉터에서 예외 발생 시
![image](https://github.com/user-attachments/assets/4b3475d5-69d8-478d-bfe1-10ec999c15df)

---
## 결론 - 인증/인가 인터셉터가 적용되지 않은 경우 요청 흐름
![image](https://github.com/user-attachments/assets/bcd39577-c42e-4aa7-a81c-aced26894540)
